export type ServiceLocation = {
  name: string;
  href: string;
};

export type ServiceAreaGroup = {
  slug: string;
  name: string;
  /** The city's own landing page, once it has one. */
  href?: string;
  locations: ServiceLocation[];
};

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/'/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Builds a location link as `/mobile-tyre-fitting-{slug}`; pass `slug` when the name doesn't slugify cleanly. */
function location(name: string, slug = slugify(name)): ServiceLocation {
  return { name, href: `/mobile-tyre-fitting-${slug}` };
}

function group(
  name: string,
  locations: (string | ServiceLocation)[],
  href?: string,
): ServiceAreaGroup {
  return {
    slug: slugify(name),
    name,
    href,
    locations: locations.map((item) => (typeof item === "string" ? location(item) : item)),
  };
}

export const serviceAreas: ServiceAreaGroup[] = [
  group("Bury", [
    "Prestwich",
    "Radcliffe",
    "Ramsbottom",
    "Tottington",
    "Whitefield",
    "Affetside",
    "Ainsworth",
    "Birtle",
    "Edenfield",
    "Fishpool",
    "Greenmount",
    "Heap Bridge",
    "Holcombe",
    "Simister",
    "Summerseat",
    "Unsworth",
  ], "/bury/mobile-tyre-service"),
  group("Bolton", [
    "Blackrod",
    "Farnworth",
    "Horwich",
    "Kearsley",
    "Little Lever",
    "South Turton",
    "Westhoughton",
    "Astley Bridge",
    "Breightmet",
    "Bromley Cross",
    "Deane",
    "Eagley",
    "Great Lever",
    "Hall i' th' Wood",
    "Harwood",
    "Lostock",
    "Smithills",
    "Tonge Moor",
  ]),
  group("Manchester", [
    "Blackley",
    "Cheetham Hill",
    "Chorlton-cum-Hardy",
    "Didsbury",
    "Beswick",
    "Fallowfield",
    "Hulme",
    "Moss Side",
    "Newton Heath",
    "Northenden",
    "Ringway",
    "Rusholme",
    "Withington",
    "Wythenshawe",
    "Longsight",
    "Ancoats",
    "Ardwick",
    "Burnage",
    "Clayton",
    "Collyhurst",
    "Firswood",
    "Gorton",
    "Harpurhey",
    "Ladybarn",
    "Levenshulme",
    "Mancunian Way area",
    "Miles Platting",
    "Moston",
    "Openshaw",
    "Whalley Range",
  ]),
  group("Oldham", [
    "Chadderton",
    "Failsworth",
    "Lees",
    "Royton",
    "Saddleworth",
    "Shaw and Crompton",
    "Hollinwood",
    "Uppermill",
    "Austerlands",
    "Delph",
    "Denshaw",
    "Derker",
    "Diggle",
    "Dobcross",
    "Failsworth Pole",
    "Fitton Hill",
    "Glodwick",
    "Grasscroft",
    "Hathershaw",
    "Lydgate",
    "Scouthead",
    "Springhead",
    "Waterhead",
    "Werneth",
  ]),
  group("Rochdale", [
    "Heywood",
    "Littleborough",
    "Middleton",
    "Milnrow",
    "Newhey",
    "Wardle",
    "Castleton",
    "Whitworth",
    "Bamford",
    "Belfield",
    "Crown Oil area/Heywood",
    "Dearnley",
    "Healey",
    "Hurstead",
    "Kirkholt",
    "Norden",
    "Shawclough",
    "Smallbridge",
    "Summit",
    "Syke",
    "Thrum Hall",
  ]),
  group("Salford", [
    "Cadishead",
    "Eccles",
    "Greengate",
    "Pendlebury",
    "Pendleton",
    "Swinton",
    "Walkden",
    "Worsley",
    "Irlam",
    "Little Hulton",
    "Agecroft",
    "Broughton",
    "Clifton",
    "Higher Broughton",
    "Irlam o' th' Height",
    "Kersal",
    "Lower Broughton",
    "MediaCityUK",
    "Monton",
    "Ordsall",
    "Patricroft",
    "Salford Quays",
    "Swinton Park",
    "Weaste",
    "Winton",
  ]),
  group("Stockport", [
    "Bramhall",
    "Bredbury",
    "Cheadle",
    "Gatley",
    "Hazel Grove",
    "Heaton Chapel",
    "Heaton Mersey",
    "Heaton Moor",
    "Heaton Norris",
    "Marple",
    "Marple Bridge",
    "Mellor",
    "Reddish",
    "Romiley",
    "Cheadle Hulme",
    "Heald Green",
    "High Lane",
    "Woodley",
    "Adswood",
    "Bosden",
    "Brinnington",
    "Compstall",
    "Davenport",
    "Disley",
    "Edgeley",
    "Great Moor",
    "Offerton",
  ]),
  group("Tameside", [
    "Ashton-under-Lyne",
    "Audenshaw",
    "Broadbottom",
    "Denton",
    "Droylsden",
    "Dukinfield",
    "Hattersley",
    "Hollingworth",
    "Hyde",
    "Longdendale",
    "Mossley",
    "Mottram-in-Longdendale",
    "Stalybridge",
    "Flowery Field",
    "Gee Cross",
    "Guide Bridge",
    "Hartshead",
    "Hurst",
    "Lumb Lane",
    "Millbrook",
    "Newton",
    "Stalyhill",
  ]),
  group("Trafford", [
    "Stretford",
    "Altrincham",
    "Bowdon",
    "Hale",
    "Old Trafford",
    "Sale",
    "Timperley",
    "Urmston",
    "Ashton upon Mersey",
    "Davyhulme",
    "Flixton",
    "Partington",
    "Baguley",
    "Broadheath",
    "Brooklands",
    "Carrington",
    "Dunham Massey",
    "Priory Green",
    "Sale Moor",
    "Urmston Meadows",
  ]),
  group("Wigan", [
    "Abram",
    "Ashton-in-Makerfield",
    "Aspull",
    "Astley",
    "Atherton",
    "Bryn",
    "Golborne",
    "Higher End",
    "Hindley",
    "Ince-in-Makerfield",
    "Leigh",
    "Orrell",
    "Shevington",
    "Standish",
    "Tyldesley",
    "Winstanley",
    "Billinge",
    "Hindley Green",
    "Lowton",
    "Pemberton",
    "Bickershaw",
    "Haigh",
    "Newtown",
    "Platt Bridge",
    "Scholes",
    "Spring View",
    "Worthington",
  ]),
  group("Motorways & Roads", [
    "M6",
    "M60",
    "M602",
    "M61",
    "M56",
    "M62",
    "M66",
    location("A627(M)", "a627"),
    "M67",
    location("A57(M)", "a57"),
    "Wilmslow Road",
  ]),
];
